# Generated by Django 4.2.5 on 2023-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewomen', '0003_alter_women_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create']},
        ),
        migrations.RemoveIndex(
            model_name='women',
            name='sitewomen_w_time_cr_a05d48_idx',
        ),
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['time_create'], name='sitewomen_w_time_cr_9084b8_idx'),
        ),
    ]
