# Generated by Django 4.2.5 on 2023-11-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewomen', '0005_category_women_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='women',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='sitewomen.category'),
        ),
        migrations.AddField(
            model_name='women',
            name='tags2',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sitewomen.tagpost2'),
        ),
    ]
