# Generated by Django 4.2.5 on 2023-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewomen', '0007_husband_women_husband'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
